name: Build and push

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  push:
    name: Build and push
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./compose/app/Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ghcr.io/petterhj/pjuuldex:latest
